--employees 에서 전체 내용 조회
SELECT * FROM EMPLOYEES e;

FIRST NAME, LAST_name, job_id;
SELECT First_name, LAST_name, job_id
FROM EMPLOYEES e ; -- Fob 조회

SELECT * FROM EMPLOYEES e ;
-- 사원번호가 176인 사람의 LAST_NAME과 DEPARTMENT_ID 조회
SELECT
	LAST_NAME,
	DEPARTMENT_ID
FROM
	EMPLOYEES
WHERE
	EMPLOYEE_ID = 176;

-- 연봉이 12000 이상 되는 직원들의 LAST_NAME과 SALARY 조회
SELECT
	LAST_NAME,
	SALARY
FROM
	EMPLOYEES e
WHERE

	SALARY >= 12000;

-- 연봉이 5000에서 12000의 범위 이외인 사람들의 LAST_NAME과 SALARY 조회
SELECT
	LAST_NAME,
	SALARY
FROM
	EMPLOYEES e
WHERE
	SALARY < 5000
	OR SALARY > 12000;

-- 부서전호가 20, 50인 부서에서 근무하는 사원들의 LAST_NAME, DEPARTMENT_ID 조회
SELECT
	LAST_NAME,
	DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	DEPARTMENT_ID IN (20, 50);

-- last_name 오름차순, department_id 오름차순 정렬
SELECT
	LAST_NAME,
	DEPARTMENT_ID
FROM
	EMPLOYEES e
WHERE
	DEPARTMENT_ID IN (20, 50)
ORDER BY LAST_NAME, DEPARTMENT_ID;

-- 커미션을 버는 모든 사원들의 LAST_NAME, SALARY, COMMISION_PCT 조회
SELECT
	LAST_NAME,
	SALARY,
	COMMISSION_PCT
FROM
	EMPLOYEES e
WHERE
	COMMISSION_PCT IS NOT NULL
ORDER BY SALARY DESC, COMMISSION_PCT DESC;

-- SALARY가 2500, 3500, 7000이 아니며, job이 SA_REP나 ST_CLERK인 사원 조회
SELECT
	*
FROM
	EMPLOYEES e
WHERE
	SALARY NOT IN (2500, 3500, 7000)
	AND job_id IN ('SA_REP', 'ST_CLERK');

-- 2017-01-01 ~ 2017-12-31 사이에 고용된 사원들의 last_name, employee_id, hire_date 조회
-- hire_date 내림차순 정렬
SELECT
	LAST_NAME,
	EMPLOYEE_ID,
	HIRE_DATE
FROM
	EMPLOYEES e
WHERE
	HIRE_DATE BETWEEN '2017-01-01' AND '2017-12-31'
ORDER BY HIRE_DATE DESC;

